// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

// Package http represents the interface "fermyon:spin/http".
package http

import (
	httptypes "github.com/rajatjindal/wasip2-golang/fermyon/spin/http-types"
	"github.com/ydnar/wasm-tools-go/cm"
)

// HTTPError represents the enum "fermyon:spin/http-types#http-error".
//
// See [httptypes.HTTPError] for more information.
type HTTPError = httptypes.HTTPError

// Request represents the record "fermyon:spin/http-types#request".
//
// See [httptypes.Request] for more information.
type Request = httptypes.Request

// Response represents the record "fermyon:spin/http-types#response".
//
// See [httptypes.Response] for more information.
type Response = httptypes.Response

// SendRequest represents function "fermyon:spin/http#send-request".
//
//	send-request: func(req: request) -> result<response, http-error>
//
//go:nosplit
func SendRequest(req Request) cm.OKResult[Response, HTTPError] {
	var result cm.OKResult[Response, HTTPError]
	wasmimport_SendRequest(req, &result)
	return result
}

//go:wasmimport fermyon:spin/http send-request
//go:noescape
func wasmimport_SendRequest(req Request, result *cm.OKResult[Response, HTTPError])
