// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

// Package inboundredis represents the interface "fermyon:spin/inbound-redis".
package inboundredis

import (
	redistypes "github.com/rajatjindal/wasip2-golang/fermyon/spin/redis-types"
	"github.com/ydnar/wasm-tools-go/cm"
)

// Error represents the enum "fermyon:spin/redis-types#error".
//
// See [redistypes.Error] for more information.
type Error = redistypes.Error

// Payload represents the list "fermyon:spin/redis-types#payload".
//
// See [redistypes.Payload] for more information.
type Payload = redistypes.Payload

// HandleMessage represents function "fermyon:spin/inbound-redis#handle-message".
//
// The entrypoint for a Redis handler.
//
//	handle-message: func(message: payload) -> result<_, error>
//
//go:nosplit
func HandleMessage(message Payload) cm.ErrResult[struct{}, Error] {
	var result cm.ErrResult[struct{}, Error]
	wasmimport_HandleMessage(message, &result)
	return result
}

//go:wasmimport fermyon:spin/inbound-redis handle-message
//go:noescape
func wasmimport_HandleMessage(message Payload, result *cm.ErrResult[struct{}, Error])
