spin_manifest_version = 2

[application]
name = "wasip2-golang"
version = "0.2.0"
authors = ["Rajat Jindal <rajatjindal83@gmail.com>"]
description = ""


[[trigger.http]]
route = "/..."
component = "wasip2-golang"

[component.wasip2-golang]
source = "main.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]

[component.wasip2-golang.build]
command = "tinygo build -target=wasip2 -tags=purego -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
