// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

// Package stderr represents the interface "wasi:cli/stderr@0.2.0-rc-2023-11-10".
package stderr

import (
	streams "github.com/rajatjindal/wasip2-golang/wasi/io/streams/v0.2.0-rc-2023-11-10"
)

// OutputStream represents the resource "wasi:io/streams@0.2.0-rc-2023-11-10#output-stream".
//
// See [streams.OutputStream] for more information.
type OutputStream = streams.OutputStream

// GetStderr represents function "wasi:cli/stderr@0.2.0-rc-2023-11-10#get-stderr".
//
//	get-stderr: func() -> own<output-stream>
//
//go:nosplit
func GetStderr() OutputStream {
	return wasmimport_GetStderr()
}

//go:wasmimport wasi:cli/stderr@0.2.0-rc-2023-11-10 get-stderr
//go:noescape
func wasmimport_GetStderr() OutputStream
