// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

// Package foo represents the interface "rj:ns/foo@2.0.0".
package foo

// Greet represents function "rj:ns/foo@2.0.0#greet".
//
//	greet: func() -> string
//
//go:nosplit
func Greet() string {
	var result string
	wasmimport_Greet(&result)
	return result
}

//go:wasmimport rj:ns/foo@2.0.0 greet
//go:noescape
func wasmimport_Greet(result *string)
