// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

// Package foobar represents the interface "foo:foo/foo-bar".
package foobar

import (
	"github.com/rajatjindal/wasip2-golang/wasi/io/streams"
)

// OutputStream represents the resource "wasi:io/streams@0.2.0#output-stream".
//
// See [streams.OutputStream] for more information.
type OutputStream = streams.OutputStream

// Hello represents function "foo:foo/foo-bar#hello".
//
//	hello: func()
//
//go:nosplit
func Hello() {
	wasmimport_Hello()
}

//go:wasmimport foo:foo/foo-bar hello
//go:noescape
func wasmimport_Hello()
