// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

// Package terminalstdin represents the interface "wasi:cli/terminal-stdin@0.2.0-rc-2023-10-18".
//
// An interface providing an optional `terminal-input` for stdin as a
// link-time authority.
package terminalstdin

import (
	terminalinput "github.com/rajatjindal/wasip2-golang/wasi/cli/terminal-input/v0.2.0-rc-2023-10-18"
	"github.com/ydnar/wasm-tools-go/cm"
)

// TerminalInput represents the resource "wasi:cli/terminal-input@0.2.0-rc-2023-10-18#terminal-input".
//
// See [terminalinput.TerminalInput] for more information.
type TerminalInput = terminalinput.TerminalInput

// GetTerminalStdin represents function "wasi:cli/terminal-stdin@0.2.0-rc-2023-10-18#get-terminal-stdin".
//
// If stdin is connected to a terminal, return a `terminal-input` handle
// allowing further interaction with it.
//
//	get-terminal-stdin: func() -> option<own<terminal-input>>
//
//go:nosplit
func GetTerminalStdin() cm.Option[TerminalInput] {
	var result cm.Option[TerminalInput]
	wasmimport_GetTerminalStdin(&result)
	return result
}

//go:wasmimport wasi:cli/terminal-stdin@0.2.0-rc-2023-10-18 get-terminal-stdin
//go:noescape
func wasmimport_GetTerminalStdin(result *cm.Option[TerminalInput])
