// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

// Package postgres represents the interface "fermyon:spin/postgres".
package postgres

import (
	rdbmstypes "github.com/rajatjindal/wasip2-golang/fermyon/spin/rdbms-types"
	"github.com/ydnar/wasm-tools-go/cm"
)

// ParameterValue represents the variant "fermyon:spin/rdbms-types#parameter-value".
//
// See [rdbmstypes.ParameterValue] for more information.
type ParameterValue = rdbmstypes.ParameterValue

// PgError represents the variant "fermyon:spin/postgres#pg-error".
//
// General purpose error.
//
//	variant pg-error {
//		success,
//		connection-failed(string),
//		bad-parameter(string),
//		query-failed(string),
//		value-conversion-failed(string),
//		other-error(string),
//	}
type PgError cm.Variant[uint8, string, string]

// PgErrorSuccess returns a [PgError] of case "success".
func PgErrorSuccess() PgError {
	var data struct{}
	return cm.New[PgError](0, data)
}

// Success returns true if [PgError] represents the variant case "success".
func (self *PgError) Success() bool {
	return cm.Tag(self) == 0
}

// PgErrorConnectionFailed returns a [PgError] of case "connection-failed".
func PgErrorConnectionFailed(data string) PgError {
	return cm.New[PgError](1, data)
}

// ConnectionFailed returns a non-nil *[string] if [PgError] represents the variant case "connection-failed".
func (self *PgError) ConnectionFailed() *string {
	return cm.Case[string](self, 1)
}

// PgErrorBadParameter returns a [PgError] of case "bad-parameter".
func PgErrorBadParameter(data string) PgError {
	return cm.New[PgError](2, data)
}

// BadParameter returns a non-nil *[string] if [PgError] represents the variant case "bad-parameter".
func (self *PgError) BadParameter() *string {
	return cm.Case[string](self, 2)
}

// PgErrorQueryFailed returns a [PgError] of case "query-failed".
func PgErrorQueryFailed(data string) PgError {
	return cm.New[PgError](3, data)
}

// QueryFailed returns a non-nil *[string] if [PgError] represents the variant case "query-failed".
func (self *PgError) QueryFailed() *string {
	return cm.Case[string](self, 3)
}

// PgErrorValueConversionFailed returns a [PgError] of case "value-conversion-failed".
func PgErrorValueConversionFailed(data string) PgError {
	return cm.New[PgError](4, data)
}

// ValueConversionFailed returns a non-nil *[string] if [PgError] represents the variant case "value-conversion-failed".
func (self *PgError) ValueConversionFailed() *string {
	return cm.Case[string](self, 4)
}

// PgErrorOtherError returns a [PgError] of case "other-error".
func PgErrorOtherError(data string) PgError {
	return cm.New[PgError](5, data)
}

// OtherError returns a non-nil *[string] if [PgError] represents the variant case "other-error".
func (self *PgError) OtherError() *string {
	return cm.Case[string](self, 5)
}

// RowSet represents the record "fermyon:spin/rdbms-types#row-set".
//
// See [rdbmstypes.RowSet] for more information.
type RowSet = rdbmstypes.RowSet

// Execute represents function "fermyon:spin/postgres#execute".
//
// execute command to the database: insert, update, delete
//
//	execute: func(address: string, statement: string, params: list<parameter-value>)
//	-> result<u64, pg-error>
//
//go:nosplit
func Execute(address string, statement string, params cm.List[ParameterValue]) cm.ErrResult[uint64, PgError] {
	var result cm.ErrResult[uint64, PgError]
	wasmimport_Execute(address, statement, params, &result)
	return result
}

//go:wasmimport fermyon:spin/postgres execute
//go:noescape
func wasmimport_Execute(address string, statement string, params cm.List[ParameterValue], result *cm.ErrResult[uint64, PgError])

// Query represents function "fermyon:spin/postgres#query".
//
// query the database: select
//
//	query: func(address: string, statement: string, params: list<parameter-value>)
//	-> result<row-set, pg-error>
//
//go:nosplit
func Query(address string, statement string, params cm.List[ParameterValue]) cm.OKResult[RowSet, PgError] {
	var result cm.OKResult[RowSet, PgError]
	wasmimport_Query(address, statement, params, &result)
	return result
}

//go:wasmimport fermyon:spin/postgres query
//go:noescape
func wasmimport_Query(address string, statement string, params cm.List[ParameterValue], result *cm.OKResult[RowSet, PgError])
