// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

// Package inboundhttp represents the interface "fermyon:spin/inbound-http@2.0.0".
package inboundhttp

import (
	httptypes "github.com/rajatjindal/wasip2-golang/fermyon/spin/http-types"
)

// Request represents the record "fermyon:spin/http-types@2.0.0#request".
//
// See [httptypes.Request] for more information.
type Request = httptypes.Request

// Response represents the record "fermyon:spin/http-types@2.0.0#response".
//
// See [httptypes.Response] for more information.
type Response = httptypes.Response

// HandleRequest represents function "fermyon:spin/inbound-http@2.0.0#handle-request".
//
//	handle-request: func(req: request) -> response
//
//go:nosplit
func HandleRequest(req Request) Response {
	var result Response
	wasmimport_HandleRequest(req, &result)
	return result
}

//go:wasmimport fermyon:spin/inbound-http@2.0.0 handle-request
//go:noescape
func wasmimport_HandleRequest(req Request, result *Response)

type Interface interface {
	HandleRequest(req Request) Response
}

var instance Interface
