// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

// Package preopens represents the interface "wasi:filesystem/preopens@0.2.0-rc-2023-11-10".
package preopens

import (
	types "github.com/rajatjindal/wasip2-golang/wasi/filesystem/types/v0.2.0-rc-2023-11-10"
	"github.com/ydnar/wasm-tools-go/cm"
)

// Descriptor represents the resource "wasi:filesystem/types@0.2.0-rc-2023-11-10#descriptor".
//
// See [types.Descriptor] for more information.
type Descriptor = types.Descriptor

// GetDirectories represents function "wasi:filesystem/preopens@0.2.0-rc-2023-11-10#get-directories".
//
// Return the set of preopened directories, and their path.
//
//	get-directories: func() -> list<tuple<own<descriptor>, string>>
//
//go:nosplit
func GetDirectories() cm.List[cm.Tuple[Descriptor, string]] {
	var result cm.List[cm.Tuple[Descriptor, string]]
	wasmimport_GetDirectories(&result)
	return result
}

//go:wasmimport wasi:filesystem/preopens@0.2.0-rc-2023-11-10 get-directories
//go:noescape
func wasmimport_GetDirectories(result *cm.List[cm.Tuple[Descriptor, string]])
