// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

// Package incominghandler represents the interface "wasi:http/incoming-handler@0.2.0-rc-2023-10-18".
//
// The `wasi:http/incoming-handler` interface is meant to be exported by
// components and called by the host in response to a new incoming HTTP
// response.
//
// NOTE: in Preview3, this interface will be merged with
// `wasi:http/outgoing-handler` into a single `wasi:http/handler` interface
// that takes a `request` parameter and returns a `response` result.
package incominghandler

import (
	types "github.com/rajatjindal/wasip2-golang/wasi/http/types/v0.2.0-rc-2023-10-18"
)

// IncomingRequest represents the resource "wasi:http/types@0.2.0-rc-2023-10-18#incoming-request".
//
// See [types.IncomingRequest] for more information.
type IncomingRequest = types.IncomingRequest

// ResponseOutparam represents the resource "wasi:http/types@0.2.0-rc-2023-10-18#response-outparam".
//
// See [types.ResponseOutparam] for more information.
type ResponseOutparam = types.ResponseOutparam

// Handle represents function "wasi:http/incoming-handler@0.2.0-rc-2023-10-18#handle".
//
// The `handle` function takes an outparam instead of returning its response
// so that the component may stream its response while streaming any other
// request or response bodies. The callee MUST write a response to the
// `response-outparam` and then finish the response before returning. The `handle`
// function is allowed to continue execution after finishing the response's
// output stream. While this post-response execution is taken off the
// critical path, since there is no return value, there is no way to report
// its success or failure.
//
//	handle: func(request: own<incoming-request>, response-out: own<response-outparam>)
//
//go:nosplit
func Handle(request IncomingRequest, responseOut ResponseOutparam) {
	wasmimport_Handle(request, responseOut)
}

//go:wasmimport wasi:http/incoming-handler@0.2.0-rc-2023-10-18 handle
//go:noescape
func wasmimport_Handle(request IncomingRequest, responseOut ResponseOutparam)
