// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

// Package stdin represents the interface "wasi:cli/stdin@0.2.0-rc-2023-10-18".
package stdin

import (
	streams "github.com/rajatjindal/wasip2-golang/wasi/io/streams/v0.2.0-rc-2023-10-18"
)

// InputStream represents the resource "wasi:io/streams@0.2.0-rc-2023-10-18#input-stream".
//
// See [streams.InputStream] for more information.
type InputStream = streams.InputStream

// GetStdin represents function "wasi:cli/stdin@0.2.0-rc-2023-10-18#get-stdin".
//
//	get-stdin: func() -> own<input-stream>
//
//go:nosplit
func GetStdin() InputStream {
	return wasmimport_GetStdin()
}

//go:wasmimport wasi:cli/stdin@0.2.0-rc-2023-10-18 get-stdin
//go:noescape
func wasmimport_GetStdin() InputStream
